---
- name: Setup pre-requisite python3 packages
  yum:
    state: present
    name:
    - git
    - python3-pip

- name: Setup pre-requisite pip3 packages
  pip:
    name:
    - virtualenv
    state: present
    executable: /usr/bin/pip3

- name: Copy requirements.txt to target for k8s virtualenv
  copy:
    src: ./files/requirements_k8s.txt
    dest: /tmp/requirements_k8s.txt

- name: "Create virtualenv k8s"
  pip:
    requirements: /tmp/requirements_k8s.txt
    virtualenv: "{{ k8s_virtualenv_home }}"
    virtualenv_site_packages: no
    virtualenv_command: /usr/local/bin/virtualenv

- name: Ensure system Python3 has selinux library installed
  pip:
    state: present
    executable: /usr/bin/pip3
    name: selinux
    version: 0.2.1
