apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: infinispan-provisioner
rules:
  - verbs:
      - create
      - update
      - patch
      - delete
    apiGroups:
      - infinispan.org
    resources:
      - infinispans
  - verbs:
      - get
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    resourceNames:
      - infinispans.infinispan.org
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - infinispan.org
    resources:
      - infinispans
  - verbs:
      - '*'
    apiGroups:
      - infinispan.org
    resources:
      - infinispans
