apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kafka-cluster-provisioner
  labels:
    app: strimzi
rules:
  - verbs:
      - create
      - update
      - patch
      - delete
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkabridges
  - verbs:
      - create
      - update
      - patch
      - delete
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkaconnects
  - verbs:
      - create
      - update
      - patch
      - delete
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkaconnects2is
  - verbs:
      - create
      - update
      - patch
      - delete
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkamirrormakers
  - verbs:
      - create
      - update
      - patch
      - delete
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkas
  - verbs:
      - create
      - update
      - patch
      - delete
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkatopics
  - verbs:
      - create
      - update
      - patch
      - delete
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkausers
  - verbs:
      - get
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    resourceNames:
      - kafkabridges.kafka.strimzi.io
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkabridges
  - verbs:
      - get
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    resourceNames:
      - kafkaconnects.kafka.strimzi.io
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkaconnects
  - verbs:
      - get
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    resourceNames:
      - kafkaconnects2is.kafka.strimzi.io
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkaconnects2is
  - verbs:
      - get
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    resourceNames:
      - kafkamirrormakers.kafka.strimzi.io
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkamirrormakers
  - verbs:
      - get
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    resourceNames:
      - kafkas.kafka.strimzi.io
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkas
  - verbs:
      - get
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    resourceNames:
      - kafkatopics.kafka.strimzi.io
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkatopics
  - verbs:
      - get
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    resourceNames:
      - kafkausers.kafka.strimzi.io
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkausers
  - verbs:
      - '*'
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkabridges
  - verbs:
      - '*'
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkaconnects
  - verbs:
      - '*'
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkaconnects2is
  - verbs:
      - '*'
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkamirrormakers
  - verbs:
      - '*'
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkas
  - verbs:
      - '*'
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkatopics
  - verbs:
      - '*'
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkausers
