kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: kogito-quarkus-ubi8-s2i
  annotations:
    openshift.io/display-name: Platform for building Kogito based on Quarkus
    openshift.io/provider-display-name: Kie Group.
spec:
  tags:
    - name: '0.7.0'
      annotations:
        description: Platform for building Kogito based on Quarkus
        iconClass: icon-jbpm
        tags: builder,kogito,quarkus
        supports: quarkus
        version: '0.7.0'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: quay.io/kiegroup/kogito-quarkus-ubi8-s2i:0.7.0