kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: kogito-quarkus-ubi8
  annotations:
    openshift.io/display-name: Runtime image for Kogito based on Quarkus native image
    openshift.io/provider-display-name: Kie Group.
spec:
  tags:
    - name: '0.7.0'
      annotations:
        description: Runtime image for Kogito based on Quarkus native image
        iconClass: icon-jbpm
        tags: runtime,kogito,quarkus
        supports: quarkus
        version: '0.7.0'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: quay.io/kiegroup/kogito-quarkus-ubi8:0.7.0