apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kogito-provisioner
rules:
  - verbs:
      - create
      - update
      - patch
      - delete
    apiGroups:
      - app.kiegroup.org
    resources:
      - kogitoapps
  - verbs:
      - create
      - update
      - patch
      - delete
    apiGroups:
      - app.kiegroup.org
    resources:
      - kogitodataindices
  - verbs:
      - create
      - update
      - patch
      - delete
    apiGroups:
      - app.kiegroup.org
    resources:
      - kogitoinfras
  - verbs:
      - create
      - update
      - patch
      - delete
    apiGroups:
      - app.kiegroup.org
    resources:
      - kogitojobsservices
  - verbs:
      - get
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    resourceNames:
      - kogitoapps.app.kiegroup.org
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - app.kiegroup.org
    resources:
      - kogitoapps
  - verbs:
      - get
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    resourceNames:
      - kogitodataindices.app.kiegroup.org
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - app.kiegroup.org
    resources:
      - kogitodataindices
  - verbs:
      - get
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    resourceNames:
      - kogitoinfras.app.kiegroup.org
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - app.kiegroup.org
    resources:
      - kogitoinfras
  - verbs:
      - get
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    resourceNames:
      - kogitojobsservices.app.kiegroup.org
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - app.kiegroup.org
    resources:
      - kogitojobsservices
  - verbs:
      - '*'
    apiGroups:
      - app.kiegroup.org
    resources:
      - kogitoapps
  - verbs:
      - '*'
    apiGroups:
      - app.kiegroup.org
    resources:
      - kogitodataindices
  - verbs:
      - '*'
    apiGroups:
      - app.kiegroup.org
    resources:
      - kogitoinfras
  - verbs:
      - '*'
    apiGroups:
      - app.kiegroup.org
    resources:
      - kogitojobsservices




