---

- name: "delete Infinispan custom resource"
  k8s:
    state: absent
    namespace: "{{ _namespace }}"
    definition: "{{ lookup('template', role_path ~ '/templates/infinispan-cluster/infinispan-cluster.yml' ) | from_yaml }}"

- name: "delete Infinispan credentials secret"
  k8s:
    state: absent
    namespace: "{{ _namespace }}"
    definition: "{{ lookup('template', role_path ~ '/templates/infinispan-cluster/infinispan-credentials-secret.yml' ) | from_yaml }}"

- name: "create Infinispan credentials secret for data index service"
  k8s:
    state: absent
    namespace: "{{ _namespace }}"
    definition: "{{ lookup('template', role_path ~ '/templates/infinispan-cluster/infinispan-credentials.yml' ) | from_yaml }}"

-