---

- name: "delete Infinispan custom resource"
  k8s:
    state: absent
    namespace: "{{ _namespace }}"
    definition: "{{ lookup('template', role_path ~ '/templates/infinispan-cluster/infinispan-cluster.yml' ) | from_yaml }}"
