---

- name: "remove infinispan provisioner rights from user user{{ user_num }} "
  k8s:
    state: absent
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('template', role_path ~ '/templates/infinispan/infinispan-provisioner-rolebinding.yml' ) | from_yaml }}"

- name: "delete Infinispan operator deployment for user user{{ user_num }}"
  k8s:
    state: absent
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('file', role_path ~ '/files/infinispan/infinispan-operator-deployment.yml' ) | from_yaml }}"

- name: "delete Infinispan operator rolebinding for user user{{ user_num }}"
  k8s:
    state: absent
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('template', role_path ~ '/templates/infinispan/infinispan-operator-rolebinding.yml' ) | from_yaml }}"

- name: "delete Infinispan operator role for user user{{ user_num }}"
  k8s:
    state: absent
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('file', role_path ~ '/files/infinispan/infinispan-operator-role.yml' ) | from_yaml }}"

- name: "delete Infinispan operator service account for user user{{ user_num }}"
  k8s:
    state: absent
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('file', role_path ~ '/files/infinispan/infinispan-operator-serviceaccount.yml' ) | from_yaml }}"
