---

- name: "create Infinispan operator service account for user user{{ user_num }}"
  k8s:
    state: present
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('file', role_path ~ '/files/infinispan/infinispan-operator-serviceaccount.yml' ) | from_yaml }}"

- name: "create Infinispan operator role for user user{{ user_num }}"
  k8s:
    state: present
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('file', role_path ~ '/files/infinispan/infinispan-operator-role.yml' ) | from_yaml }}"

- name: "create Infinispan operator rolebinding for user user{{ user_num }}"
  k8s:
    state: present
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('template', role_path ~ '/templates/infinispan/infinispan-operator-rolebinding.yml' ) | from_yaml }}"
