---
- name: set namespace
  set_fact:
    _namespace: "{{ namespace_prefix }}{{ user_num }}"

- name: "create namespace {{ _namespace }}"
  k8s:
    state: present
    definition: "{{ lookup('template', role_path ~ '/templates/namespace.j2' ) | from_yaml }}"

- name: "give user user{{ user_num }} admin rights in namespace {{ _namespace }}"
  k8s:
    state: present
    namespace: "{{ _namespace }}"
    definition: "{{ lookup('template', role_path ~ '/templates/namespace-admin-rb.j2' ) | from_yaml }}"

- name: "Strimzi workload for user user{{ user_num }}"
  include_tasks: workload_per_project_strimzi.yml
