apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kogito-service-viewer
  annotations:
    org.kie.kogito/managed-by: Kogito Operator
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - get
      - watch
      - update
      - patch