kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kogito-operator
subjects:
  - kind: ServiceAccount
    name: kogito-operator
roleRef:
  kind: Role
  name: kogito-operator
  apiGroup: rbac.authorization.k8s.io