---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: infinispan-operator
subjects:
  - kind: ServiceAccount
    name: infinispan-operator
    namespace: {{ _namespace }}
roleRef:
  kind: Role
  name: infinispan-operator
  apiGroup: rbac.authorization.k8s.io
